version: '3'
services:
  web:
    image: education-vuejs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    logging:
      options:
        max-size: "10m"
        max-file: "3"