version: "3"
services:
  vue-app:
    command: >
      sh -c "yarn serve"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: education-vuejs
    restart: always
    ports:
      - "3000:80"
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge